// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.24.3
// source: api/crypto-facade/crypto-facade.proto

package crypto_facade

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Chain int32

const (
	Chain_UNKNOWN_CHAIN Chain = 0
	Chain_POLYGON       Chain = 1
)

// Enum value maps for Chain.
var (
	Chain_name = map[int32]string{
		0: "UNKNOWN_CHAIN",
		1: "POLYGON",
	}
	Chain_value = map[string]int32{
		"UNKNOWN_CHAIN": 0,
		"POLYGON":       1,
	}
)

func (x Chain) Enum() *Chain {
	p := new(Chain)
	*p = x
	return p
}

func (x Chain) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Chain) Descriptor() protoreflect.EnumDescriptor {
	return file_api_crypto_facade_crypto_facade_proto_enumTypes[0].Descriptor()
}

func (Chain) Type() protoreflect.EnumType {
	return &file_api_crypto_facade_crypto_facade_proto_enumTypes[0]
}

func (x Chain) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Chain.Descriptor instead.
func (Chain) EnumDescriptor() ([]byte, []int) {
	return file_api_crypto_facade_crypto_facade_proto_rawDescGZIP(), []int{0}
}

type Token int32

const (
	Token_UNKNOWN_TOKEN Token = 0
	Token_MATIC         Token = 1
)

// Enum value maps for Token.
var (
	Token_name = map[int32]string{
		0: "UNKNOWN_TOKEN",
		1: "MATIC",
	}
	Token_value = map[string]int32{
		"UNKNOWN_TOKEN": 0,
		"MATIC":         1,
	}
)

func (x Token) Enum() *Token {
	p := new(Token)
	*p = x
	return p
}

func (x Token) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Token) Descriptor() protoreflect.EnumDescriptor {
	return file_api_crypto_facade_crypto_facade_proto_enumTypes[1].Descriptor()
}

func (Token) Type() protoreflect.EnumType {
	return &file_api_crypto_facade_crypto_facade_proto_enumTypes[1]
}

func (x Token) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Token.Descriptor instead.
func (Token) EnumDescriptor() ([]byte, []int) {
	return file_api_crypto_facade_crypto_facade_proto_rawDescGZIP(), []int{1}
}

type AcceptCryptoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Chain Chain `protobuf:"varint,1,opt,name=chain,proto3,enum=crypto_facade.Chain" json:"chain,omitempty"`
	Token Token `protobuf:"varint,2,opt,name=token,proto3,enum=crypto_facade.Token" json:"token,omitempty"`
}

func (x *AcceptCryptoRequest) Reset() {
	*x = AcceptCryptoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_crypto_facade_crypto_facade_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AcceptCryptoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptCryptoRequest) ProtoMessage() {}

func (x *AcceptCryptoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_crypto_facade_crypto_facade_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptCryptoRequest.ProtoReflect.Descriptor instead.
func (*AcceptCryptoRequest) Descriptor() ([]byte, []int) {
	return file_api_crypto_facade_crypto_facade_proto_rawDescGZIP(), []int{0}
}

func (x *AcceptCryptoRequest) GetChain() Chain {
	if x != nil {
		return x.Chain
	}
	return Chain_UNKNOWN_CHAIN
}

func (x *AcceptCryptoRequest) GetToken() Token {
	if x != nil {
		return x.Token
	}
	return Token_UNKNOWN_TOKEN
}

type AcceptCryptoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
}

func (x *AcceptCryptoResponse) Reset() {
	*x = AcceptCryptoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_crypto_facade_crypto_facade_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AcceptCryptoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptCryptoResponse) ProtoMessage() {}

func (x *AcceptCryptoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_crypto_facade_crypto_facade_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptCryptoResponse.ProtoReflect.Descriptor instead.
func (*AcceptCryptoResponse) Descriptor() ([]byte, []int) {
	return file_api_crypto_facade_crypto_facade_proto_rawDescGZIP(), []int{1}
}

func (x *AcceptCryptoResponse) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

var File_api_crypto_facade_crypto_facade_proto protoreflect.FileDescriptor

var file_api_crypto_facade_crypto_facade_proto_rawDesc = []byte{
	0x0a, 0x25, 0x61, 0x70, 0x69, 0x2f, 0x63, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x2d, 0x66, 0x61, 0x63,
	0x61, 0x64, 0x65, 0x2f, 0x63, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x2d, 0x66, 0x61, 0x63, 0x61, 0x64,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x63, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x5f,
	0x66, 0x61, 0x63, 0x61, 0x64, 0x65, 0x22, 0x6d, 0x0a, 0x13, 0x41, 0x63, 0x63, 0x65, 0x70, 0x74,
	0x43, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2a, 0x0a,
	0x05, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x14, 0x2e, 0x63,
	0x72, 0x79, 0x70, 0x74, 0x6f, 0x5f, 0x66, 0x61, 0x63, 0x61, 0x64, 0x65, 0x2e, 0x43, 0x68, 0x61,
	0x69, 0x6e, 0x52, 0x05, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x12, 0x2a, 0x0a, 0x05, 0x74, 0x6f, 0x6b,
	0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x14, 0x2e, 0x63, 0x72, 0x79, 0x70, 0x74,
	0x6f, 0x5f, 0x66, 0x61, 0x63, 0x61, 0x64, 0x65, 0x2e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x05,
	0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x30, 0x0a, 0x14, 0x41, 0x63, 0x63, 0x65, 0x70, 0x74, 0x43,
	0x72, 0x79, 0x70, 0x74, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x2a, 0x27, 0x0a, 0x05, 0x43, 0x68, 0x61, 0x69, 0x6e,
	0x12, 0x11, 0x0a, 0x0d, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x5f, 0x43, 0x48, 0x41, 0x49,
	0x4e, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x50, 0x4f, 0x4c, 0x59, 0x47, 0x4f, 0x4e, 0x10, 0x01,
	0x2a, 0x25, 0x0a, 0x05, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x11, 0x0a, 0x0d, 0x55, 0x4e, 0x4b,
	0x4e, 0x4f, 0x57, 0x4e, 0x5f, 0x54, 0x4f, 0x4b, 0x45, 0x4e, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05,
	0x4d, 0x41, 0x54, 0x49, 0x43, 0x10, 0x01, 0x32, 0x67, 0x0a, 0x0c, 0x43, 0x72, 0x79, 0x70, 0x74,
	0x6f, 0x46, 0x61, 0x63, 0x61, 0x64, 0x65, 0x12, 0x57, 0x0a, 0x0c, 0x41, 0x63, 0x63, 0x65, 0x70,
	0x74, 0x43, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x12, 0x22, 0x2e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x6f,
	0x5f, 0x66, 0x61, 0x63, 0x61, 0x64, 0x65, 0x2e, 0x41, 0x63, 0x63, 0x65, 0x70, 0x74, 0x43, 0x72,
	0x79, 0x70, 0x74, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e, 0x63, 0x72,
	0x79, 0x70, 0x74, 0x6f, 0x5f, 0x66, 0x61, 0x63, 0x61, 0x64, 0x65, 0x2e, 0x41, 0x63, 0x63, 0x65,
	0x70, 0x74, 0x43, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x42, 0x33, 0x5a, 0x31, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x66,
	0x69, 0x64, 0x65, 0x73, 0x79, 0x2d, 0x70, 0x61, 0x79, 0x2f, 0x63, 0x72, 0x79, 0x70, 0x74, 0x6f,
	0x2d, 0x66, 0x61, 0x63, 0x61, 0x64, 0x65, 0x3b, 0x63, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x5f, 0x66,
	0x61, 0x63, 0x61, 0x64, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_crypto_facade_crypto_facade_proto_rawDescOnce sync.Once
	file_api_crypto_facade_crypto_facade_proto_rawDescData = file_api_crypto_facade_crypto_facade_proto_rawDesc
)

func file_api_crypto_facade_crypto_facade_proto_rawDescGZIP() []byte {
	file_api_crypto_facade_crypto_facade_proto_rawDescOnce.Do(func() {
		file_api_crypto_facade_crypto_facade_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_crypto_facade_crypto_facade_proto_rawDescData)
	})
	return file_api_crypto_facade_crypto_facade_proto_rawDescData
}

var file_api_crypto_facade_crypto_facade_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_api_crypto_facade_crypto_facade_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_crypto_facade_crypto_facade_proto_goTypes = []interface{}{
	(Chain)(0),                   // 0: crypto_facade.Chain
	(Token)(0),                   // 1: crypto_facade.Token
	(*AcceptCryptoRequest)(nil),  // 2: crypto_facade.AcceptCryptoRequest
	(*AcceptCryptoResponse)(nil), // 3: crypto_facade.AcceptCryptoResponse
}
var file_api_crypto_facade_crypto_facade_proto_depIdxs = []int32{
	0, // 0: crypto_facade.AcceptCryptoRequest.chain:type_name -> crypto_facade.Chain
	1, // 1: crypto_facade.AcceptCryptoRequest.token:type_name -> crypto_facade.Token
	2, // 2: crypto_facade.CryptoFacade.AcceptCrypto:input_type -> crypto_facade.AcceptCryptoRequest
	3, // 3: crypto_facade.CryptoFacade.AcceptCrypto:output_type -> crypto_facade.AcceptCryptoResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_crypto_facade_crypto_facade_proto_init() }
func file_api_crypto_facade_crypto_facade_proto_init() {
	if File_api_crypto_facade_crypto_facade_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_crypto_facade_crypto_facade_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AcceptCryptoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_crypto_facade_crypto_facade_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AcceptCryptoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_crypto_facade_crypto_facade_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_crypto_facade_crypto_facade_proto_goTypes,
		DependencyIndexes: file_api_crypto_facade_crypto_facade_proto_depIdxs,
		EnumInfos:         file_api_crypto_facade_crypto_facade_proto_enumTypes,
		MessageInfos:      file_api_crypto_facade_crypto_facade_proto_msgTypes,
	}.Build()
	File_api_crypto_facade_crypto_facade_proto = out.File
	file_api_crypto_facade_crypto_facade_proto_rawDesc = nil
	file_api_crypto_facade_crypto_facade_proto_goTypes = nil
	file_api_crypto_facade_crypto_facade_proto_depIdxs = nil
}
